---
# tasks file for acme-proxy

- name: 'Prepare a directory for storing the remote transfer scripts.'
  file:
    path: '{{ acme__scripts_dir }}'
    state: 'directory'

- name: 'Install script to transfer the certificate from the remote hosts'
  template:
    src: 'acme-remote_cert.sh.j2'
    dest: '{{ acme__scripts_dir }}/acme-remote_{{ acme__cert_name }}.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'
  vars:
    acme__cert_name: '{{ item.domain[0]
                        if ( item.domain is iterable and
                                not item.domain is string)
                        else item.domain }}'
    acme__cert_path: '{{ acme__config_dir }}/{{ acme__cert_name }}'
    acme__certificate: '{{ acme__cert_path }}.crt'
    acme__remote_proxy: '{{ item.sign }}'
  with_items: '{{ acme__domain }}'

- name: 'Write a cron job to be run once a month for certificate transfer'
  cron:
    name: 'acme-remote_{{ acme__cert_name }}'
    job: '{{ acme__scripts_dir }}/acme-remote_{{ acme__cert_name }}.sh 2>> {{ acme__log_dir }}/acme-remote_{{ acme__cert_name }}.log'
    user: '{{ acme__user }}'
    minute: '{{ acme__cron_minute }}'
    hour: '{{ acme__cron_hour }}'
    day: '{{ acme__cron_day }}'
    month: '{{ acme__cron_month }}'
    weekday: '{{ acme__cron_weekday }}'
  vars:
    acme__cert_name: '{{ item.domain[0]
                        if ( item.domain is iterable and
                                not item.domain is string)
                        else item.domain }}'
  with_items: '{{ acme__domain }}'

